MIB relocated to Ceph repo
SUSE/prometheus-webhook-snmp pull request #34
Opened 2021-09-22 23:38 UTC by pcuzner

The MIB has been relocated to the main Ceph repo, so
the MIB file and docs needed to be updated to reflect
this change.

Signed-off-by: Paul Cuzner <pcuzner@redhat.com>

2021-09-23 09:34 UTC, sebastian-philipp commented
https://github.com/ceph/ceph/pull/43274

2021-09-28 07:35 UTC, votdev commented
I would like to keep all files as they are in this repository, but i'm fine with adding the `SNMP Integration` section in the README.

2021-09-28 07:36 UTC, votdev requested changes
I would like to keep all files that are removed by this PR, but i'm fine with adding the SNMP Integration section in the README.

2021-09-30 06:58 UTC, votdev commented on README.md
> -# SNMP schema
Please keep that section.

2021-09-30 06:59 UTC, votdev commented on PROMETHEUS-ALERT-CEPH-MIB.txt
> -PROMETHEUS-ALERT-MIB DEFINITIONS ::= BEGIN
Please keep that file

2021-10-05 02:05 UTC, pcuzner commented
@votdev I'm a bit confused with keeping the MIB in two places. The MIB you've created is using the ceph oid, so shouldn't it exist in only one place? And if so, why would you want to reference information here that could fall out of date relating to the schema?

2021-10-12 22:12 UTC, pcuzner commented
@votdev I'll close this PR. I was trying to rationalise how the ceph MIB is consumed across the projects - but I can see now that that doesn't make sense here. Apologies.

Your MIB  has now been merged into ceph, and I have an update to the alerts pending. All of which means the ceph MIb will be receiving a lot of changes in the near future.

2021-10-12 22:12 UTC, closed without merging

2021-10-21 10:37 UTC, votdev commented
Sorry for answering so late, was fully occupied by the Bubbles project. I also had my concerns about that because the `prometheus-webhook-snmp` project is a plugin for `Prometheus` and is only indirectly related to `Ceph`.